spring:
#  datasource:
#    url: jdbc:mysql://192.168.2.227:3306/gisdm_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: zbcx
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.194.123.8:5432/gis?stringtype=unspecified&ApplicationName=tutorial
    username: postgres
    password: zgisadmin

token:
  wl:
    secretKey: ioap_wl_token_key